---
abstract: 'Survey installed modules and determine the specific distribution versions they came from'
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires:
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Surveyor
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
requires:
  CPAN::DistnameInfo: 0
  Carp: 0
  Compress::Zlib: 0
  Config: 0
  DBI: 0
  DB_File: 0
  Data::Dumper::Concise: 0
  Digest::SHA: 0
  Fcntl: 0
  File::Basename: 0
  File::Fetch: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec: 0
  File::Spec::Unix: 0
  Getopt::Long: 0
  LWP::Simple: 0
  List::Util: 0
  MLDBM: 0
  Memoize: 0
  MetaCPAN::API: 0.32
  Module::CoreList: 0
  Module::Metadata: 0
  Storable: 0
  Try::Tiny: 0
  URI: 0
  autodie: 0
  constant: 0
  perl: 5.006
  strict: 0
  version: 0
  warnings: 0
resources:
  homepage: https://github.com/semuel/Dist-Surveyor
  repository: https://github.com/semuel/Dist-Surveyor.git
version: 0.003
