---
abstract: 'Survey installed modules and determine the specific distribution versions they came from'
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Surveyor
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
requires:
  CPAN::DistnameInfo: 0
  Compress::Zlib: 0
  JSON: 0
  LWP::UserAgent: 0
  Module::CoreList: 0
  Module::Metadata: 0
  perl: 5.006
  version: 0
resources:
  homepage: https://github.com/semuel/Dist-Surveyor
  repository: https://github.com/semuel/Dist-Surveyor.git
version: 0.008
